# Windows host required for the AzureFileCopy@2 task
pool:
  vmImage: 'vs2017-win2016'

# Retrieve the hugo executable
steps:
- powershell: |
    Invoke-WebRequest -Uri $(HugoReleasePath) -O $(Build.BinariesDirectory)/hugo.zip
    Expand-Archive -LiteralPath $(Build.BinariesDirectory)/hugo.zip -DestinationPath $(Build.BinariesDirectory)
  displayName: 'Get Hugo'

# Build site contents
- script: $(Build.BinariesDirectory)/hugo.exe -d $(Build.StagingDirectory)
  displayName: 'Build Site Contents'

# Copy contents to Azure blob
- task: AzureFileCopy@2
  displayName: 'Publish Site Contents'
  inputs:
    sourcePath: $(Build.StagingDirectory)
    azureConnectionType: connectedServiceNameARM
    azureSubscription: default
    destination: azureBlob
    storage: reynoldsbd
    containerName: www
