pool:
  vmImage: 'vs2017-win2016'

steps:
- powershell: |
    Invoke-WebRequest -Uri $(HugoReleasePath) -O $(Build.BinariesDirectory)/hugo.zip
    Expand-Archive -LiteralPath $(Build.BinariesDirectory)/hugo.zip -DestinationPath $(Build.BinariesDirectory)
  displayName: 'Get Hugo'

- script: |
    $(Build.BinariesDirectory)/hugo.exe -d $(Build.StagingDirectory)
  displayName: 'Build Site Contents'

- task: AzureFileCopy@2
  displayName: 'Publish Site Contents'
  inputs:
    sourcePath: $(Build.StagingDirectory)
    azureConnectionType: connectedServiceNameARM
    azureSubscription: default
    destination: azureBlob
    storage: reynoldsbd
    containerName: www
    #additionalArgumentsForBlobCopy
