title: Bobby Reynolds
languageCode: en-us
relativeURLs: true

markup:
  highlight:
    codeFences: true
    guessSyntax: true

theme: focus
params:
  accentColor: '#FFA54C'

menu:
  main:
  - identifier: posts
    name: All Posts
    title: All Posts
    url: /posts/
    weight: 1
  - identifier: about
    name: About
    title: About
    url: /about/
    weight: 2
