languageCode = "en-us"
title = "For Fun & Profit"
pygmentsCodeFences = true
relativeURLs = true
# uglyurls = true

# Theme settings
theme = "focus"
sectionPagesMenu = "main"
[params]
    accentColor = "#FFA54C"
