name: Build and Deploy
on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout Sources
      uses: actions/checkout@v2

    - name: Set Up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 0.74.3
        extended: true

    - name: Install NPM Dependencies
      run: npm ci
      working-directory: ./themes/focus

    - name: Build Static Content
      run: hugo -b https://reynoldsbd.net/

    - name: Deploy to Web Server
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
        REMOTE_HOST: reynoldsbd.net
        REMOTE_USER: blog
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: public/*
        TARGET: /var/www/blog/
        ARGS: -rt --delete
