name: Build and Deploy
on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout Sources
      uses: actions/checkout@v2

    - name: Install Deployment Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DEPLOYMENT_KEY }}
        name: id_ed25519
        known_hosts: ${{ secrets.DEPLOYMENT_KNOWN_HOSTS }}
        config: ${{ secrets.DEPLOYMENT_CONFIG }}

    - name: Set Up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 0.67.0
        extended: true

    - name: Build Static Content
      run: hugo -b https://reynoldsbd.net/

    - name: Deploy to Web Server
      run: rsync -rt --delete ./public/* reynoldsbd.net:/usr/local/www/blog/
